/* babel written by Arctica
 *
 *  wiz+ command, can be cast on a player of level less than or equal to yours
 * babel <player>
 * effect lasts for 5 minutes or until player is 'cured'
 * when the spell is cast, awiz+ sees:
 * <player1> has cast the Babel spell on <player2>.
 * the victim is given no warning that the spell has been cast on him
 * while under the influence of the spell, whenever the player uses:
 * chat, anon, gchat, say, wish, wiz, ist, awiz, demi, shout or any other
 * mode of communication....
 * his message is converted to one of the following surreal messages, selected
 * at random
*/

char *babeltext[] = {
"I can't seem to get the wrapper off",
"Help me somebody - a cuttlefish is nibbling my watermelons!",
"For the love of Mike, please stop saying such things...",
"Do you remember what happened to my larynx?",
"Don't stop... that feels nice...",
"Tell Bob to stop hassling me!",
"It'll take more than a mule to remove the lid, I'll bet",
"Fortunes are made and lost in the twinkling of a baboon",
"Sheesh!  I am surrounded by wasps of low intellectual capacity",
"Don't talk to ME about microcosms, young lady!",
"Yeah I know - I spent the entire weekend eating varnish.",
"I'm contractually obliged to stay on this mud for four years",
"I trod on a world war two mine the other day - stings a bit",
"Anyone know a good recipe for lentils and cheese?",
"Cool!  She's here",
"Hey I've gone blind!!!  Hmm, so it's true what they say...",
"Good grief!  Look at the ears on this dude!",
"It's probably pronounced 'yerp' or something",
"Speak for yourself, I've never done a typo in my lief",
"I doubt it - unless it was a very small banana",
"Lemon curry?",
"Wow!!  You're the first octogenarian mudder I'VE ever met...",
"Puff stop following me around!  I know I'm cute but really...",
"If you could visit any point in time, what time would you choose?",
"Leopards are Africa's smallest herbivorous amphibians",
"Mind you, they don't do that in Nepal, hehe",
"I'll be back later - I'm just going to have some cheese",
"My goodness, it's hot in this fridge",
"If I spontaneously combust, can someone please pick up my laundry?",
"Yup, it's three hundred and sixty five days until this time next year",
"Can someone please code a NoManish command...?",
"Not right now - ask me later on",
"<chuckle> yeah, they do have funny-shaped leaves",
"What can I use to clean my VDU?",
"Cool!  I'm three inches taller than I was last night!",
"Hey!  I think I just accidentally discovered a cure for asthma!",
"Ack - just ruptured my spleen - brb",
"My keys are soapy - what's been going on here??",
"Arctica's archimedes sure is a fine computer...",
"Does the sun seem smaller to you...?",
"The ocean is like, really deep, apparently",
"If you see Fishnu can you tell him I'm sorry I called him Vishnu?",
"...not the least of which is a triangular blackberry pie",
"I'm going to build a wizroom out of wattle and daub",
"Yuck - I have a boil on my toe and it's oozing",
"Not usually - unless it's a VERY hot day...",
"What the heck does noxypickle MEAN, anyway???",
"Scoop up the walrus droppings and serve them with lettuce",
"My conscience tells me this is wrong, but... it's fun!",
"*blush* that's kinda personal...",
"Who stuck this dirty teaspoon back in the sugar bowl??",
"Not surprisingly, the crocodile's name was Derek",
"I've got toenail clippings coming out of my ears",
"That is without doubt the finest example of contemporary literature",
"Wise words, mate, wise words indeed",
"I could dig pretty fast if I had a spade or something",
"You would not BELIEVE what I just heard...",
"I'd like to take this opportunity to pour cement on my sponge",
"I have a large house in Antigua, but the roof is a bit smelly",
"Tell me what to do with this piece of string...",
"I'm not a gambler as such, but I bet I'm shorter without my high heels",
"Coal?  isn't that a bit, um, black...?",
"My favourite colour is fourteen",
"Yes I am but please don't tell anyone",
"There's too much grass in the world... I'm thinking of starting a cull",
"I have no aptitude for climbing mountains higher than 22,000 feet",
"That aeroplane has its landing lights on!",
"Ouch - I just got a paper cut from an email",
"This castle is seriously damp",
"Can somebody please come and kiss me?",
"Hey that's not fair!  Please un-babel me at once!",
"The photophores on my belly spell out the word 'bamboo'",
"I think I left my car keys in the warm haven",
"Mancini is cool - I loved that pink panther music",
"I'm afraid I've had rather a lot to drink... can someone help me up?",
"For a wild animal, I'm unusually tame...",
"If I don't respond immediately, just talk louder",
"Where's the um... the um... oh, never mind - i've found it",
"Is it me, or does it get noticeably darker at night...?",
"I'm not entirely sure what you mean by that little remark...",
"Eek!  my body appears to consist entirely of polystyrene beads!",
"I seem to have grown a vestigial third arm overnight",
"Hey has anyone seen that new film with whatsisname in...?",
"My nostrils are for sale!  please place your bids now",
"Space is really empty, except for one or two molecules here and there",
"Soft drinks are available in the foyer",
"It's a kind of shallow bay with seaweed-covered rocks around it",
"Chocolate toothpaste...?",
"I have a sudden craving for cheese on toast...",
"Napoleon had a wishbone but kept it covered up",
"This sandstone is really crumbly... oh hang on, sorry, it's just sand",
"I bet I'm the only person here who has a giraffe-shaped modem",
"I can walk faster than I can run",
"Prometheus turned me into a newt!",
"Hey, you should hear this song :) it's cool",
"Birds can be quite large or quite small, depending on the type",
"I'm a lot more interesting than people realise!",
"Don't try the chimp's patience - he can be a little tetchy",
"I don't work for a living, I live for a working!",
"Get down off your soapbox, dude, it doesn't impress anyone",
"That reminds me of a rather amusing incident in a furniture shop recently...",
"Eww gross - that sneeze caught me by surprise - green slime everywhere",
"Oh no!  my condor just broke out of his cage... again!",
"Snakes are obedient farm animals, but their milk tastes nasty",
"I've popped up in all sorts of places, including Burma",
"It's SNOW joke, Hamburglar, ha ha ha ha ha ha ha....",
"If you stand on top of the mountain you can see the midnight sun",
"It's just one of those new-fangled contraptions, you know",
"What's the difference between a giraffe and a fork lift truck?",
"Don't be spotless - it's bordering on the unlikely",
"Inhaling pepper doesn't make you sneeze - it's just psychological",
"Paper doesn't 'flow'!  It's too solid!",
"The ice in the Arctic is surprisingly warm",
"Don't blame mangoes - there are other criminal fruit",
"Of course, the REALLY big clouds are usually made of tinsel",
"My in-tray is nearly an inch longer than my out-tray",
"I wouldn't trust an insurance salesman who was made of tin",
"I could escape from any jail in the world - and frequently have",
"I was conceived in a deep-water submersible in the North Atlantic",
"I'll weather the weather, whether wet or whatever",
"The resourcefulness of Rotty is beyond dispute",
"Please could you move your car - this is a private parking area",
"All my dreams come true - once I woke up and I was a hamster",
"My mjolnir's broken - can I have a new one please?",
"Come dig with me in the Burgess Shale!",
"I confess that my love for Tinky knows no bounds",
"I think Bob is smarter than I am...",
"Anyone up for a game of strip poker?",
"My fingertips speak Welsh",
"You can do quite a lot of things with wax",
"On turnips up-trained goals are voluminous pant-gorgle dutch errggghhh",
"String him up from the yard-arm, me hearties!",
"Have you ever BEEN to the East Pole??  It's HUGE!!!!",
"Industrial effluent makes a really good toothpaste",
"I'm not having enough fun.  Entertain me!",
"I once drowned in the Red Sea - thank heaven for reincarnation",
"If I stare at my video while chewing, the digital display goes wobbly",
"What's this???  I'm not a mule, you know!",
"I've not been to Uruguay in at least a week",
"Anyone want to take a shower with me?",
"Let bygones be dugongs",
"Kali is a credit to her uniform",
"Watch out, Kali's leading an army of plank-wielding peoples to take over the world!",
"Can anyone remember the name of that movie with the big shark..?",
"I am not entirely sure that I do not think I am not what I seem...",
"Norman!  Get out of the apple tree!  You know the beetles love your spine",
"Sea creatures never have to wash",
"Your average octopus is about as smart as a house cat",
"The end of my pen keeps falling off and it's NOT funny",
"A foot pump?  why would I want to pump up my foot??",
"I just wrote a cool virus :) anyone want a copy?",
"I once saw a photo of a flea infested with mites... cool!",
"A large furry foot",
"Oops... I think I just severely upset a nest of large hornets...",
"Before the wheel, what did people used to say was the greatest invention?",
"Eek!  a fart with a lump in it...  whoops! - brb",
"I once CLIMBED Mt Bandilbar...  beat that!",
"I just struck a deal assuring my place in the cosmos",
"*sigh* good grief I miss whatsisname...",
"I'm a dyslexic atheist... I don't believe in dogs",
"The egg came before the chicken - it stands to reason",
"If time is money, is time the root of all evil?",
"Twenty-four!",
"More than two handfuls is two wastes",
"Eek!  I just glued my fingers to the keys",
"Release the vicious dogs!  i'm going in!",
"Apples?  APPLES????  I want CHEESE!!!",
"Anyone mind if I recite a passage from King Lear?",
"Did you know that 'pestilences' is an anagram of 'select penis'?",
"Binary fission?  nah, I prefer more conventional reproductive methods",
"I have amassed a vast fortune in the textiles industry",
"Gosh, it's certainly late for the time of year",
"I spent the whole of Tuesday with only one leg",
"I have taken to saying 'rofl' irl instead of laughing - sad huh?",
"Witness the extraordinary regenerative powers of the starfish!",
"Serial shoplifters are really quite pleasant once you get to know them",
"Haddock???  rofl!",
"Accountancy is a lot less interesting than people believe",
"I'm not really into music... I prefer the squelch of farmyard manure",
"I firmly believe everything I see on TV",
"Well, I have to go - laters all",
"I'd rather be broke than have no money at all",
"Yawn, and the world yawns with you... see?  you're all yawning!!",
"My toenail cheese is harder to extract than usual",
"My entire body is normal apart from my left knee, which isn't",
"The uses of whipped cream are beyond counting",
"I have this shirt but I never wear it",
"I have contracted a virulent disease from my telephone :(",
"Whenever I put my car into reverse, the engine explodes",
"This sentence was not said by me at all but by somebody else",
"The point on Earth which is farthest from any land is in the sea",
"Oh great - now my keyboard's going to be infested with ants",
"I'm sky-diving with my computer... we've hit terminal velocity!",
"I'm getting that maternal urge...",
"I think I shall take up the floorboards and lay down the law",
"I went shopping the other day and it didn't rain",
"Yeah, apart from that other time which I've forgotten about",
"There were six of them before, but there might be eight by now",
"My long hair has got seven of them kind of wrapped up in the curls",
"I'm not a politician per se, but I do enjoy wearing rubber gear",
"Tonight's the big night!  wish me luck everyone",
"If koalas are sleepy they're much less dangerous",
"I tend to grow things organically at this time of the day",
"Go for it!  but um, no violence... unless you really feel like it...",
"Join my campaign for more colours on the muds!",
"Fart in the bath - it's fun blowing bubbles!",
"My additive motor is complete electrically, so they say.  Bah!",
"in another ten days it will be a lot later than now",
"I'm not sure if I ought to stay hungry or feel full up",
"I am attempting a mind-meld with my computer",
"Lawks a-mussy-me! what a ran tam gamly gamly over the medley crun",
"Yum.... excuse me while I go and wash the cheese off my fingers",
"The ancient Greeks?  nice language, but I wouldn't sleep with one of them",
"Yesterday I visited a medium and spoke with my long-dead tortoise",
"I can see the future - feel free to ask me for accurate predictions",
"I've just upgraded to a furry mouse :)",
"What ho, Squiffy!  Top hole over the briny!",
"I should be a lot happier had I a few feathers about me",
"I've been jailed for making obscene clones fall... :("
};
