char   *__add_codes(int, int, Bodypart *, int, char *);
void    __generalmsg(int, int, Bodypart *, char *);
int     applyfunc(int, int func(Bodypart *, int, FILE *), int, FILE *);
int     take_bodypart_helper(Bodypart *, int, FILE *);
void    check_parts(int, int, Bodypart *, Boolean);
Boolean test_wear(int, int);
Boolean cant_wear(int, int);
void    hospital(void);
void    exit_hospital(void);
void    list_parts(int);
void    confirm_challenge(char *);
void    calc_ac(int);
void    flee(int, Boolean);
void    wear_item(int, int);
void    player_died(int, int, int);
void    set_player_parts(int);
void    hit_player(int, int, int);
void    removeobj(Boolean, int, int);
void    killplr(int, int);
void    reset_armor(Boolean, int);
int     dambyitem(int, int);
int     wears_shield(int);
void    set_vital(int);
void    show_vital(int);
void    breakitem(int);
void    setpfighting(int, int);
void    scatter_potions(void);
char    *str_color(int);
char    *mag_color(int);

void    loot(int);
void    wieldcom(void);
void    lootcom(void);
void    armorcom(void);
void    crawlcom(void);
void    equcom(void);
void    restorecom(void);
void    killcom(void);
void    challengecom(void);
Boolean set_weapon(int plr, int wpn);

