# Do not delete this line, the makedep program requires it. #
# Last Updated: Wed Apr 21 21:55:34 EST 1999                #
#############################################################

# Dependencies for the MUD source code
#
