#ifndef _COMMANDS_H
#define _COMMANDS_H

int     aliased_mob (int);
void    sneakcom(void);
void    pickcom(void);
void    backstabcom(void);
void    suggestcom(void);
void    bashcom(void);
void	oraclecom(char com[10]);
void	wherecom(void);
void    ringcom(void);
void	rubcom(void);
void	fillcom(void);
void	lookcom(void);
void	examcom(void);
void	sys_reset(void);
void    confirm_reset(char *);
void    reset(void);
void	incom(Boolean inv);
void	resetcom(int flags);
void	unveilcom(char *unv_pass);
void	posecom(void);
void	praycom(void);
void	reviewcom(void);
void	shoutcom(void);
void	scorecom(void);
void	sitcom(void);
void	standcom(int plr);
void	pncom(void);
void	bugcom(void);
void	typocom(void);
void	helpcom(void);
void	help2(char *cont);
void	help3(char *cont);
void	help4(char *cont);
void	help5(char *cont);
void	help6(char *cont);
void	help7(char *cont);
int	showhelp(char *verb);
void	questcom(void);
void	infocom(void);
void	globalcom(void);
void	unalias(int player);
void	unpolymorph(int player);
Boolean	disp_file(char *fname, FILE *f);
void	flowercom(void);
void	ticklecom(void);
void	petcom(void);
void	polymorph(int plx,int turns);
int	find_pretender(int plx);
void	aliascom(void);
Boolean	disp_file(char *fname, FILE *f);
void	togglecom(int flg, char on[80], char off[80]);
void	gossipcom(void);
void	anoncom(void);
void	klockcom(char *passwd);
void	conversecom(void);
void	lsaycom(void);
void	langcom(void);
void	policycom(void);
void	optionscom(void);
void	setpager(void);
void	becom(char *passwd);
void	mbullcom(void);
void	wbullcom(void);
void	abullcom(void);
void	followcom(void);
void	losecom(void);
void	treasurecom(void);
void	emptycom(void);
void	rollcom(void);
void	chatcom(void);
void	channelcom(void);
void	forgetcom(void);
void	forgetlist(void);
void	beepcom(void);
void	qdonecom(void);
void	asmortalcom(void);
void	levelscom(void);
void	promptcom(void);
void	fingercom(void);
void	wavecom(void);
void	lightcom(void);
void	extinguishcom(void);
void	blowcom(void);
void	pushcom(void);
void	wishcom(void);
void	comparecom(void);
void	ubullcom(void);

#define RES_TEST  0x01  /* Perform check for pflag */

#endif
